create table coach (gender tinyint, birthday datetime(6), id bigint not null, firstname varchar(255), lastname varchar(255), password varchar(255), phone varchar(255), username varchar(255), primary key (id)) engine=InnoDB;
create table coach_seq (next_val bigint) engine=InnoDB;
insert into coach_seq values ( 1 );
create table coach (gender tinyint, birthday datetime(6), id bigint not null, firstname varchar(255), lastname varchar(255), password varchar(255), phone varchar(255), username varchar(255), primary key (id)) engine=InnoDB;
create table coach_seq (next_val bigint) engine=InnoDB;
insert into coach_seq values ( 1 );
create table coach (gender tinyint, birthday datetime(6), id bigint not null, firstname varchar(255), lastname varchar(255), password varchar(255), phone varchar(255), username varchar(255), primary key (id)) engine=InnoDB;
create table coach_seq (next_val bigint) engine=InnoDB;
insert into coach_seq values ( 1 );
create table coach (gender tinyint, birthday datetime(6), id bigint not null, firstname varchar(255), lastname varchar(255), password varchar(255), phone varchar(255), username varchar(255), primary key (id)) engine=InnoDB;
create table coach_seq (next_val bigint) engine=InnoDB;
insert into coach_seq values ( 1 );
